### PR TITLE
fixes for helm issues and importing yipee.yaml itself

### PR DESCRIPTION
**Pull request by jrryjcksn**
Fixes for following issues:
- Namespaced unknown kinds preventing import (of yipee.yaml for example)
- Incorrectly capitalized name of values.yaml in import
- Improper handling of strings containing numbers, yaml booleans, and spaces in generated helm charts
- Improper handling of '.' in helm chart keys
- Improper handling of '/' in helm variable names

### CODE REVIEW

**Review by D3nn — APPROVED** [review]
With you at the helm, I'm sure we are ready to be importing this into the master branch.

**Review by jd3quist — APPROVED** [review]
👍

**Review by markemeis — COMMENTED** [review]
Awesome job finding and fixing these issues.  Are there any changes required in the UI?  Specifically around the dotted annotation names?

**Comment by jrryjcksn** [comment]
Shouldn't be any UI changes required...

**Pull request merged**
